//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_data
    {
        public int log_id { get; set; }
        public int emp_id { get; set; }
        public string time { get; set; }
        public System.DateTime date { get; set; }
        public string ip_address { get; set; }
        public string pc_name { get; set; }
        public byte is_authorised { get; set; }
    }
}
