//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class saprfcdbEntities : DbContext
    {
        public saprfcdbEntities()
            : base("name=saprfcdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<cost_center> cost_center { get; set; }
        public virtual DbSet<domain> domains { get; set; }
        public virtual DbSet<function> functions { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<log_data> log_data { get; set; }
        public virtual DbSet<p_area> p_area { get; set; }
        public virtual DbSet<p_sub_area> p_sub_area { get; set; }
        public virtual DbSet<plant> plants { get; set; }
        public virtual DbSet<req_tkt_type> req_tkt_type { get; set; }
        public virtual DbSet<request_ticket> request_ticket { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<url> urls { get; set; }
        public virtual DbSet<url_type> url_type { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_group> user_group { get; set; }
        public virtual DbSet<user_permission> user_permission { get; set; }
        public virtual DbSet<user_sub_group> user_sub_group { get; set; }
        public virtual DbSet<YH_ACT_EMP_LIST> YH_ACT_EMP_LIST { get; set; }
    }
}
