//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plant
    {
        public int loc_id { get; set; }
        public string plant_name { get; set; }
        public int plant_code { get; set; }
        public byte is_active { get; set; }
        public int plant_id { get; set; }
        public int cost_center { get; set; }
    }
}
