//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class req_tkt_type
    {
        public string type_name { get; set; }
        public string type_desc { get; set; }
        public byte is_active { get; set; }
        public int type_id { get; set; }
    }
}
