//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request_ticket
    {
        public int req_tkt_type { get; set; }
        public System.DateTime req_tkt_start_date { get; set; }
        public int req_tkt_status { get; set; }
        public int req_tkt_emp_id { get; set; }
        public System.DateTime req_tkt_end_date { get; set; }
        public int req_tkt_id { get; set; }
    }
}
