//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class url
    {
        public int url_id { get; set; }
        public string menu_name { get; set; }
        public string url_value { get; set; }
        public int url_type { get; set; }
        public byte is_active { get; set; }
    }
}
