//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int emp_epf { get; set; }
        public int emp_user_grp { get; set; }
        public int emp_user_sub_grp { get; set; }
        public string emp_name { get; set; }
        public string emp_email { get; set; }
        public string emp_password { get; set; }
        public int emp_company { get; set; }
        public int emp_function { get; set; }
        public int emp_location { get; set; }
        public int emp_plant { get; set; }
        public int emp_mobile { get; set; }
        public byte is_active { get; set; }
        public int emp_id { get; set; }
    }
}
