//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permission
    {
        public int user_sub_grp_id { get; set; }
        public int url { get; set; }
        public int url_type { get; set; }
        public byte is_view { get; set; }
        public byte is_edit { get; set; }
        public byte is_active { get; set; }
        public int perm_id { get; set; }
    }
}
