//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFCWEBAPIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YH_ACT_EMP_LIST
    {
        public int EPF { get; set; }
        public string NAME { get; set; }
        public Nullable<int> LOCATION { get; set; }
        public string FUNCT { get; set; }
        public string COST_CENTER { get; set; }
        public string ENDDA { get; set; }
        public string BIRTHDA { get; set; }
    }
}
